# Generated by Django 6.0.4 on 2026-06-01 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0008_alter_resource_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100, unique=True, verbose_name='Item ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('tier', models.IntegerField(verbose_name='Tier')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='artifacts/%Y/%m/%d/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Artifact',
                'verbose_name_plural': 'Artifacts',
            },
        ),
        migrations.CreateModel(
            name='CraftingRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_amount', models.PositiveIntegerField(default=1, verbose_name='Output Amount')),
            ],
            options={
                'verbose_name': 'Crafting Recipe',
                'verbose_name_plural': 'Crafting Recipes',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100, unique=True, verbose_name='Item ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('tier', models.IntegerField(verbose_name='Tier')),
                ('enchantment', models.IntegerField(default=0, verbose_name='Enchantment')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='items/%Y/%m/%d/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='CraftingIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Amount')),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crafting.artifact')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='crafting.craftingrecipe')),
            ],
        ),
        migrations.AddField(
            model_name='craftingrecipe',
            name='output_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crafting_recipes', to='crafting.item', verbose_name='Output Item'),
        ),
    ]
