# Generated by Django 6.0.4 on 2026-06-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('bow', 'Bow'), ('crossbow', 'Crossbow'), ('sword', 'Sword'), ('axe', 'Axe'), ('dagger', 'Dagger'), ('spear', 'Spear'), ('staff', 'Staff'), ('cloth_armor', 'Cloth Armor'), ('leather_armor', 'Leather Armor'), ('plate_armor', 'Plate Armor'), ('bag', 'Bag'), ('cape', 'Cape'), ('tool', 'Tool')], max_length=30, null=True, verbose_name='Category'),
        ),
        migrations.AddConstraint(
            model_name='craftingrecipe',
            constraint=models.UniqueConstraint(fields=('output_item',), name='unique_crafting_recipe_output_item'),
        ),
    ]
