# Generated by Django 6.0.4 on 2026-06-01 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0002_item_category_and_more'),
        ('resources', '0009_alter_resource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftingingredient',
            name='resource',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'refined'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.resource'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('bow', 'Bow'), ('crossbow', 'Crossbow'), ('sword', 'Sword'), ('axe', 'Axe'), ('dagger', 'Dagger'), ('spear', 'Spear'), ('staff', 'Staff'), ('cloth_armor', 'Cloth Armor'), ('leather_armor', 'Leather Armor'), ('plate_armor', 'Plate Armor'), ('bag', 'Bag'), ('cape', 'Cape'), ('tool', 'Tool')], max_length=30, verbose_name='Category'),
        ),
    ]
