# Generated by Django 6.0.4 on 2026-05-21 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0006_remove_resource_unique_resource_by_name_tier_enchantment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('sell_price_min', models.PositiveIntegerField(default=0)),
                ('buy_price_max', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_price', to='resources.resource')),
            ],
            options={
                'unique_together': {('resource', 'city')},
            },
        ),
    ]
