# Generated by Django 6.0.4 on 2026-06-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0003_alter_craftingingredient_resource_and_more'),
        ('market', '0001_initial'),
        ('resources', '0009_alter_resource_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactMarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('sell_price_min', models.PositiveIntegerField(default=0)),
                ('buy_price_max', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Artifact Market Price',
                'verbose_name_plural': 'Artifact Market Prices',
            },
        ),
        migrations.CreateModel(
            name='ItemMarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('sell_price_min', models.PositiveIntegerField(default=0)),
                ('buy_price_max', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Item Market Price',
                'verbose_name_plural': 'Item Market Prices',
            },
        ),
        migrations.AlterModelOptions(
            name='marketprice',
            options={'verbose_name': 'Resource Market Price', 'verbose_name_plural': 'Resource Market Prices'},
        ),
        migrations.AlterUniqueTogether(
            name='marketprice',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='marketprice',
            constraint=models.UniqueConstraint(fields=('resource', 'city'), name='unique_together_resource_and_city'),
        ),
        migrations.AddField(
            model_name='artifactmarketprice',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='crafting.artifact'),
        ),
        migrations.AddField(
            model_name='itemmarketprice',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='crafting.item'),
        ),
        migrations.AddConstraint(
            model_name='artifactmarketprice',
            constraint=models.UniqueConstraint(fields=('artifact', 'city'), name='unique_together_artifact_and_city'),
        ),
        migrations.AddConstraint(
            model_name='itemmarketprice',
            constraint=models.UniqueConstraint(fields=('item', 'city'), name='unique_together_item_and_city'),
        ),
    ]
