# Generated by Django 6.0.4 on 2026-05-07 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0004_resource_delete_resources_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefiningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_amount', models.PositiveIntegerField()),
                ('output_amount', models.PositiveIntegerField()),
                ('input_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refining_input_resource', to='resources.resource')),
                ('output_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refining_output_resource', to='resources.resource')),
            ],
        ),
    ]
