# Generated by Django 6.0.4 on 2026-05-07 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refining', '0001_initial'),
        ('resources', '0004_resource_delete_resources_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refiningresource',
            name='input_resource',
            field=models.ForeignKey(limit_choices_to={'type': 'raw'}, on_delete=django.db.models.deletion.CASCADE, related_name='refining_input_resource', to='resources.resource'),
        ),
        migrations.AlterField(
            model_name='refiningresource',
            name='output_resource',
            field=models.ForeignKey(limit_choices_to={'type': 'refined'}, on_delete=django.db.models.deletion.CASCADE, related_name='refining_output_resource', to='resources.resource'),
        ),
    ]
