# Generated by Django 6.0.4 on 2026-05-07 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refining', '0002_alter_refiningresource_input_resource_and_more'),
        ('resources', '0004_resource_delete_resources_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefiningRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_amount', models.PositiveIntegerField(default=1, verbose_name='Output amount')),
                ('output_resource', models.ForeignKey(limit_choices_to={'type': 'refined'}, on_delete=django.db.models.deletion.CASCADE, related_name='refining_output_resources', to='resources.resource', verbose_name='Output resource')),
            ],
        ),
        migrations.CreateModel(
            name='RefiningIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Amount')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refining_ingredients', to='resources.resource', verbose_name='Resource')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='refining.refiningrecipe', verbose_name='Recipe')),
            ],
        ),
        migrations.DeleteModel(
            name='RefiningResource',
        ),
        migrations.AddConstraint(
            model_name='refiningrecipe',
            constraint=models.UniqueConstraint(fields=('output_resource',), name='unique_refining_recipe_output_resource'),
        ),
    ]
