# Generated by Django 6.0.4 on 2026-05-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.IntegerField()),
                ('enchantment', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('raw', 'Raw'), ('refined', 'Refined')], default='raw', max_length=10)),
            ],
        ),
    ]
