# Generated by Django 6.0.4 on 2026-05-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='res_imagine',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='res_imagine/%Y/%m/%d/', verbose_name='Res_imagine'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='enchantment',
            field=models.IntegerField(default=0, verbose_name='Enchantment'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='tier',
            field=models.IntegerField(verbose_name='Tier'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='type',
            field=models.CharField(choices=[('raw', 'Raw'), ('refined', 'Refined')], default='raw', max_length=10, verbose_name='Type'),
        ),
    ]
