# Generated by Django 6.0.4 on 2026-05-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resources_res_imagine_alter_resources_enchantment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='res_imagine',
        ),
        migrations.AddField(
            model_name='resources',
            name='res_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='res_image/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
