# Generated by Django 6.0.4 on 2026-05-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_remove_resources_res_imagine_resources_res_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Title')),
                ('tier', models.IntegerField(verbose_name='Tier')),
                ('enchantment', models.IntegerField(default=0, verbose_name='Enchantment')),
                ('type', models.CharField(choices=[('raw', 'Raw'), ('refined', 'Refined')], default='raw', max_length=10, verbose_name='Type')),
                ('res_image', models.ImageField(blank=True, default=None, null=True, upload_to='res_image/%Y/%m/%d/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('name', 'tier', 'enchantment', 'type'), name='unique_resource_by_name_tier_enchantment_type'),
        ),
    ]
