# Generated by Django 6.0.4 on 2026-05-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resource_delete_resources_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resource',
            name='unique_resource_by_name_tier_enchantment_type',
        ),
        migrations.AddField(
            model_name='resource',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='DisplayName'),
        ),
        migrations.AddField(
            model_name='resource',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ItemID'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('item_id', 'tier', 'enchantment', 'type'), name='unique_resource_by_name_tier_enchantment_type'),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name',
        ),
    ]
