# Generated by Django 6.0.4 on 2026-05-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_remove_resource_unique_resource_by_name_tier_enchantment_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resource',
            name='unique_resource_by_name_tier_enchantment_type',
        ),
        migrations.AlterField(
            model_name='resource',
            name='display_name',
            field=models.CharField(max_length=100, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='item_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Item ID'),
        ),
    ]
