# Generated by Django 6.0.4 on 2026-05-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_remove_resource_unique_resource_by_name_tier_enchantment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(blank=True, choices=[('wood', 'Wood'), ('ore', 'Ore'), ('fiber', 'Fiber'), ('hide', 'Hide'), ('stone', 'Stone')], null=True, verbose_name='Category'),
        ),
    ]
