# Generated by Django 6.0.4 on 2026-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_resource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('wood', 'Wood'), ('ore', 'Ore'), ('fiber', 'Fiber'), ('hide', 'Hide'), ('stone', 'Stone')], verbose_name='Category'),
        ),
    ]
